# Generated by Django 3.1.3 on 2020-12-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_mainteacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AlterField(
            model_name='answerorder',
            name='option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='answerpart',
            name='result',
            field=models.CharField(blank=True, choices=[('T', 'True'), ('F', 'False')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='teach',
            name='role',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Main', 'Main'), ('Normal', 'Normal')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
