# Generated by Django 3.1.3 on 2020-12-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeexam',
            name='done',
        ),
    ]
