# Generated by Django 3.1.3 on 2020-12-29 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerorder',
            unique_together={('qpresentation', 'answerid', 'studentid'), ('qpresentation', 'option', 'studentid')},
        ),
    ]
