# Generated by Django 3.1.4 on 2020-12-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_mainteacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='answerorder',
            name='studentid',
            field=models.ForeignKey(default=9999999, on_delete=django.db.models.deletion.CASCADE, to='classroom.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answerorder',
            name='answerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.answerpart'),
        ),
        migrations.AlterField(
            model_name='answerorder',
            name='option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='answerpart',
            name='answerid',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='answerpart',
            name='result',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='outcome',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.subject'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='superoutcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superoutcome_set', to='classroom.outcome'),
        ),
        migrations.AlterField(
            model_name='question',
            name='commondescriptions',
            field=models.ManyToManyField(blank=True, to='classroom.Commondescription'),
        ),
        migrations.AlterField(
            model_name='teach',
            name='role',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Main', 'Main'), ('Normal', 'Normal')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
