# Generated by Django 3.1.3 on 2020-12-29 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20201229_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='answerorders',
        ),
    ]
