# Generated by Django 3.1.3 on 2020-12-25 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20201223_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.subject'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='superoutcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superoutcome_set', to='classroom.outcome'),
        ),
    ]
