# Generated by Django 3.1.3 on 2020-12-25 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20201225_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='superoutcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superoutcome_set', to='classroom.outcome'),
        ),
    ]
